### PR TITLE
Rendering changed for the Website

### LINKED ISSUE #11: Wanted to correct this look of website rendering
image
image

As you can see because of a small problem of links the website is not rendering properly so please assign me this issue and I will try to style this page so that it looks perfect.

### PR DESCRIPTION
**Pull request by eshan1925**
Fixes #11 

Hey, @ChlorinePentoxide and @aryashah2k I have corrected the rendering of the website and in fact, I have given styles to the page. 
So if there is no issue Please merge this PR.

Thank You

### CODE REVIEW

**Comment by ChlorinePentoxide** [comment]
Thanks! Also join our discord so can be updated about future development works.

**Review by aryashah2k — COMMENTED** [review]
SWOC 20points tag added

**Comment by eshan1925** [comment]
> Thanks! Also join our discord so can be updated about future development works.

Sure ...please give me the link :)

**Comment by ChlorinePentoxide** [comment]
Discord link: https://discord.gg/Wh6MfsmK

**Pull request merged**
