### PR TITLE
Redesigned the PatternHouse homepage

### PR DESCRIPTION
**Pull request by Daksh777**

### CODE REVIEW

**Comment by Daksh777** [comment]
@aryashah2k This PR is ready to merged for SWOC as well.

**Comment by aryashah2k** [comment]
@ChlorinePentoxide , please review the PR, I will do too, once you approve, I can merge it for SWOC

**Comment by ChlorinePentoxide** [comment]
@Daksh777 A couple of suggestions
* Use a CDN to load the Bootstrap CSS code (jsdelivr or something). Our Vercel servers are not good at delivering large JS/CSS code.
* To load non-HTML code such as custom CSS/JS/Images use the Root Assets/ folder. It is directly loaded into www.patternhouse.tk/assets folder. For example, if there is a file called style.css in the Assets folder then it would be www.patternhouse.tk/assets/style.css.
* Whenever you are referencing external links like example.com then if possible try to use the https://example.com instead of the default HTTP. Cloudflare provides us with self-signed Let's Encrypt certificates. If the website used non-HTTPS links then the full SSL encryption is not rendered.
Other than that it looks fine.

**Comment by Daksh777** [comment]
Got it, I will make the changes right now.

**Comment by Daksh777** [comment]
I have removed all the unused CSS selectors from bootstrap CSS so that the website becomes lighter. Would you still like me to use the CDN for the CSS?

**Comment by ChlorinePentoxide** [comment]
As much as you can try to use the CDN directly load it onto to the repo if you cannot use a CDN

**Comment by Daksh777** [comment]
Got it

**Comment by Daksh777** [comment]
@ChlorinePentoxide In the HTML file, should I link to the non-HTML files using the PatternHouse assets URL or directly link to it (../../Assets/css/main.css)?

**Comment by ChlorinePentoxide** [comment]
Use the pattern house assets url

**Comment by Daksh777** [comment]
Could you check now?

**Comment by ChlorinePentoxide** [comment]
All good !

**Pull request merged**
